name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
        env:
          OPENWEATHER_API_KEY: ${{ secrets.7bbf422e069710e712fbd1dfa94e8628 }}

      - name: Deploy 🚀
        uses: https://daniellewoessner.github.io/Weatherdashboard2/?
        with:
          folder: build # or dist, depending on your build output directory
          branch: gh-pages
